f:
	p := fmt
	ap := va_start fmt
	t0 := ap + .integer36
	t1 := t0 - .integer36
	t2 := (int *)t1
	t3 := *t2
	param t3
	call g
	t4 := *p
	t5 := (int)t4
	param t5
	call g

static char "C"[2]	(0,'C'),(1,.integer1),
static char "C++"[4]	(0,'C'),(1,'+'),(2,'+'),(3,.integer1),
static char "va_start argument must not have reference type and must not be parenthesized"[77]	(0,'v'),(1,'a'),(2,'_'),(3,'s'),(4,'t'),(5,'a'),(6,'r'),(7,'t'),(8,' '),(9,'a'),(10,'r'),(11,'g'),(12,'u'),(13,'m'),(14,'e'),(15,'n'),(16,'t'),(17,' '),(18,'m'),(19,'u'),(20,'s'),(21,'t'),(22,' '),(23,'n'),(24,'o'),(25,'t'),(26,' '),(27,'h'),(28,'a'),(29,'v'),(30,'e'),(31,' '),(32,'r'),(33,'e'),(34,'f'),(35,'e'),(36,'r'),(37,'e'),(38,'n'),(39,'c'),(40,'e'),(41,' '),(42,'t'),(43,'y'),(44,'p'),(45,'e'),(46,' '),(47,'a'),(48,'n'),(49,'d'),(50,' '),(51,'m'),(52,'u'),(53,'s'),(54,'t'),(55,' '),(56,'n'),(57,'o'),(58,'t'),(59,' '),(60,'b'),(61,'e'),(62,' '),(63,'p'),(64,'a'),(65,'r'),(66,'e'),(67,'n'),(68,'t'),(69,'h'),(70,'e'),(71,'s'),(72,'i'),(73,'z'),(74,'e'),(75,'d'),(76,.integer1),
const char 'C'
const char .integer1
const char 'v'
const char 'a'
const char '_'
const char 's'
const char 't'
const char 'r'
const char ' '
const char 'g'
const char 'u'
const char 'm'
const char 'e'
const char 'n'
const char 'o'
const char 'h'
const char 'f'
const char 'c'
const char 'y'
const char 'p'
const char 'd'
const char '+'
const char 'b'
const char 'i'
const char 'z'
const unsigned int .integer35
const unsigned int .integer36
const unsigned int .integer37
const unsigned int .integer38
const unsigned int .integer39
const int 0
const int 1
const int 2
const int 0
const int 1
template __countof_helper
void __report_gsfailure(unsigned long long int)
void __security_check_cookie(unsigned long long int)
extern unsigned long long int __security_cookie
void __security_init_cookie(void)
void __va_start(char **,...)
typedef bool __vcrt_bool
void f(char *,...)
bool false
void g(int)
typedef long long int intptr_t
typedef long long int ptrdiff_t
typedef unsigned long long int size_t
bool true
typedef unsigned long long int uintptr_t
typedef char *va_list
template struct __vcrt_assert_va_start_is_not_reference
struct __vcrt_assert_va_start_is_not_reference<char *>
	char .dummy
	const int __the_value
	enum .tag34
	const int __the_value
	enum .tag9
	const int __the_value
	enum .tag7
	const int __the_value
	enum .tag10
	char *fmt
		char *ap
		char *p
		char *t0
		char *t1
		int *t2
		int t3
		char t4
		int t5

static char "C"[2]	(0,'C'),(1,.integer1),
static char "C++"[4]	(0,'C'),(1,'+'),(2,'+'),(3,.integer1),
static char "va_start argument must not have reference type and must not be parenthesized"[77]	(0,'v'),(1,'a'),(2,'_'),(3,'s'),(4,'t'),(5,'a'),(6,'r'),(7,'t'),(8,' '),(9,'a'),(10,'r'),(11,'g'),(12,'u'),(13,'m'),(14,'e'),(15,'n'),(16,'t'),(17,' '),(18,'m'),(19,'u'),(20,'s'),(21,'t'),(22,' '),(23,'n'),(24,'o'),(25,'t'),(26,' '),(27,'h'),(28,'a'),(29,'v'),(30,'e'),(31,' '),(32,'r'),(33,'e'),(34,'f'),(35,'e'),(36,'r'),(37,'e'),(38,'n'),(39,'c'),(40,'e'),(41,' '),(42,'t'),(43,'y'),(44,'p'),(45,'e'),(46,' '),(47,'a'),(48,'n'),(49,'d'),(50,' '),(51,'m'),(52,'u'),(53,'s'),(54,'t'),(55,' '),(56,'n'),(57,'o'),(58,'t'),(59,' '),(60,'b'),(61,'e'),(62,' '),(63,'p'),(64,'a'),(65,'r'),(66,'e'),(67,'n'),(68,'t'),(69,'h'),(70,'e'),(71,'s'),(72,'i'),(73,'z'),(74,'e'),(75,'d'),(76,.integer1),
const char 'C'
const char .integer1
const char 'v'
const char 'a'
const char '_'
const char 's'
const char 't'
const char 'r'
const char ' '
const char 'g'
const char 'u'
const char 'm'
const char 'e'
const char 'n'
const char 'o'
const char 'h'
const char 'f'
const char 'c'
const char 'y'
const char 'p'
const char 'd'
const char '+'
const char 'b'
const char 'i'
const char 'z'
const unsigned int .integer35
const unsigned int .integer36
const unsigned int .integer37
const unsigned int .integer38
const unsigned int .integer39
const int 0
const int 1
const int 2
const int 0
const int 1
template __countof_helper
void __report_gsfailure(unsigned long long int)
void __security_check_cookie(unsigned long long int)
extern unsigned long long int __security_cookie
void __security_init_cookie(void)
void __va_start(char **,...)
typedef bool __vcrt_bool
void f(char *,...)
bool false
void g(int)
typedef long long int intptr_t
typedef long long int ptrdiff_t
typedef unsigned long long int size_t
bool true
typedef unsigned long long int uintptr_t
typedef char *va_list
template struct __vcrt_assert_va_start_is_not_reference
struct __vcrt_assert_va_start_is_not_reference<char *>
	char .dummy
	const int __the_value
	enum .tag34
	const int __the_value
	enum .tag9
	const int __the_value
	enum .tag7
	const int __the_value
	enum .tag10
